---
# - import_tasks: install_docker.yml

- name: Create the docker container with MySQL
  docker_container:
      name: mysql
      image: mysql/mysql-server:5.7
      ports:
          - "3306:3306"
      volumes:
          - "/var/lib/mysql:/var/lib/mysql"
      env: "{{ mysql_authentication }}"
