version: "3"

services:
    db:
        image: mysql/mysql-server:5.7
        environment:
            - MYSQL_DATABASE=microblog
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=microblog
        restart:
            "always"
        expose:
          - "3306"

    db-test:
        image: mysql/mysql-server:5.7
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        restart:
            "always"
        expose:
          - "3306"

    prod:
        build: 
          dockerfile: docker/Dockerfile_prod
          context: .
        container_name: "microblog-production"
        links:
          - db
        ports:
            - 8000:5000
        environment:
            - SECRET_KEY=production
            - DATABASE_URL=mysql+pymysql://microblog:microblog@db:3306/microblog
        restart:
            "always"

    test:
        build:
          dockerfile: docker/Dockerfile_test
          context: .
        container_name: "microblog-test"
        links:
          - db-test
        environment:
            - SECRET_KEY=test
            - DATABASE_URL=mysql+pymysql://test:test@db-test:3306/test
