---
- name: Install dependencies
  apt:
      name:
          [
              'apt-transport-https',
              'ca-certificates',
              'curl',
              'gnupg2',
              'software-properties-common',
              'python-pip',
          ]
      update_cache: yes

- name: Pip install docker
  pip:
      name: docker

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker
  apt:
      name: docker-ce
      update_cache: yes
